# Generated by Django 5.0.4 on 2024-04-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodCatalogue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="foodItemGalary")),
                ("description", models.TextField()),
                ("price", models.IntegerField()),
                ("offer", models.BooleanField(default=False)),
            ],
        ),
    ]
